### ISSUE TITLE
Validation errors need to be fixed

### ISSUE THREAD

**Issue by red-ship-it** [casework/CASE-Implementation-PyPI-Pillow#1]
Some of the exif in the Pillow is being taken in as integers this should be strings within the controlled dictionary
```<xsd:integer> but must be a <xsd:string>```

- Also the raster `bitsperpixel` also needs to be fixed along with adding some assertions

**Comment by red-ship-it** [comment]
Have implemented a fix for this however I have highlighted these as TODO as there may be a cleaner way to do this

Have replicated the fix across both Pillow and exifread repos so they can both work with the same solution even though each lib has different outputs for these variables.

fixing ints in what should only be strings in controlled dict:

https://github.com/casework/CASE-Implementation-PyPI-Pillow/blob/b9e800de8dcac95f5166099507c769e53b3ce03f/pillow_case/exif_node_maker.py#L177-L225

fixing strings in what should only be ints:

https://github.com/casework/CASE-Implementation-PyPI-Pillow/blob/b9e800de8dcac95f5166099507c769e53b3ce03f/pillow_case/exif_node_maker.py#L253-L256

**Comment by ajnelson-nist** [comment]
This looks like a job for static type enforcement.  I have a patch brewing for `case_utils` that will show what I mean here.

**Comment by ajnelson-nist** [comment]
@red-ship-it , FYI:
https://github.com/casework/CASE-Utilities-Python/pull/16
